//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeIngredient
    {
        public int IngredientId { get; set; }
        public int RecipeId { get; set; }
        public string Preparation { get; set; }
        public int Amount { get; set; }
        public int Unit { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
